title: Today I Learned
email: pbmarcano91@gmail.com
description: >- 
  Little bits that Peter learns along the way
baseurl: "" 
url: "https://til.marcano.io"
twitter_username: pbmarcano
github_username:  pbmarcano
color: teal

permalink: /:categories/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
